# Generated by Django 4.0.2 on 2022-03-11 22:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 11, 22, 10, 53, 5553, tzinfo=utc)),
        ),
    ]
