# Generated by Django 4.0.2 on 2022-03-11 22:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0002_alter_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 11, 22, 12, 14, 196495, tzinfo=utc)),
        ),
    ]
